# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  database: etfg
  username: etfg
  password: ShortEverything!
  pool: 100
  schema_search_path: "api"

development:
  host: engine.etfg.com
  <<: *default

production:
  host: engine.etfg.com
  <<: *default
