require 'csv'

=begin
ds_id = Datasource.find_by_data_source_name('BMO').id

if File.exists?('BMO ETF Tickers - SD.csv') and (0 == DfCompositeIdentifier.where(:datasource_id => ds_id).count)
  CSV.foreach("BMO ETF Tickers - SD.csv", :headers => true) do |line|
    next if 7 != line.count or line[0].blank?
    
    DfCompositeIdentifier.create(:datasource_id => ds_id,
                                 :ticker => line[0],
                                 :name => line[1],
                                 :isin => line[2],
                                 :cusip => line[3],
                                 :figi => line[5])
   end
end
=end

if 0 == XigniteSectorMapping.count
  XigniteSectorMapping.create(:source => 'Communications', :dest => 'Communications')
  XigniteSectorMapping.create(:source => 'ConsumerDurables', :dest => 'Consumer Discretionary')
  XigniteSectorMapping.create(:source => 'ConsumerNonDurables', :dest => 'Consumer Staples')
  XigniteSectorMapping.create(:source => 'ConsumerServices', :dest => 'Consumer Discretionary')
  XigniteSectorMapping.create(:source => 'DistributionServices', :dest => 'Industrials')
  XigniteSectorMapping.create(:source => 'ElectronicTechnology', :dest => 'Technology')
  XigniteSectorMapping.create(:source => 'EnergyMinerals', :dest => 'Energy')
  XigniteSectorMapping.create(:source => 'Finance', :dest => 'Financials')
  XigniteSectorMapping.create(:source => 'HealthServices', :dest => 'Health Care')
  XigniteSectorMapping.create(:source => 'HealthTechnology', :dest => 'Health Care')
  XigniteSectorMapping.create(:source => 'IndustrialServices', :dest => 'Industrials')
  XigniteSectorMapping.create(:source => 'NonEnergyMinerals', :dest => 'Basic Materials')
  XigniteSectorMapping.create(:source => 'ProcessIndustries', :dest => 'Basic Materials')
  XigniteSectorMapping.create(:source => 'ProducerManufacturing', :dest => 'Industrials')
  XigniteSectorMapping.create(:source => 'RetailTrade', :dest => 'Consumer Discretionary')
  XigniteSectorMapping.create(:source => 'TechnologyServices', :dest => 'Technology')
  XigniteSectorMapping.create(:source => 'Transportation', :dest => 'Industrials')
  XigniteSectorMapping.create(:source => 'Utilities', :dest => 'Utilities')
end

if 0 == XigniteIndustryMapping.count
  XigniteIndustryMapping.create(:source => 'AerospaceAndDefense', :dest => 'Aerospace & Defense')
  XigniteIndustryMapping.create(:source => 'Airlines', :dest => 'Aerospace & Defense')
  XigniteIndustryMapping.create(:source => 'ApparelOrFootwear', :dest => 'Apparel & Textile Products')
  XigniteIndustryMapping.create(:source => 'ApparelOrFootwearRetail', :dest => 'Apparel & Textile Products')
  XigniteIndustryMapping.create(:source => 'InvestmentManagers', :dest => 'Asset Management')
  XigniteIndustryMapping.create(:source => 'InvestmentTrustsOrMutualFunds', :dest => 'Asset Management')  
  XigniteIndustryMapping.create(:source => 'AutoPartsOEM', :dest => 'Automotive')
  XigniteIndustryMapping.create(:source => 'AutomotiveAftermarket', :dest => 'Automotive')
  XigniteIndustryMapping.create(:source => 'MotorVehicles', :dest => 'Automotive')
  XigniteIndustryMapping.create(:source => 'MajorBanks', :dest => 'Banking')
  XigniteIndustryMapping.create(:source => 'RegionalBanks', :dest => 'Banking')
  XigniteIndustryMapping.create(:source => 'SavingsBanks', :dest => 'Banking')
  XigniteIndustryMapping.create(:source => 'Biotechnology', :dest => 'Biotech & Pharma')
  XigniteIndustryMapping.create(:source => 'PharmaceuticalsGeneric', :dest => 'Biotech & Pharma')
  XigniteIndustryMapping.create(:source => 'PharmaceuticalsMajor', :dest => 'Biotech & Pharma')
  XigniteIndustryMapping.create(:source => 'PharmaceuticalsOther', :dest => 'Biotech & Pharma')
  XigniteIndustryMapping.create(:source => 'ChemicalsAgricultural', :dest => 'Chemicals')
  XigniteIndustryMapping.create(:source => 'ChemicalsMajorDiversified', :dest => 'Chemicals')
  XigniteIndustryMapping.create(:source => 'ChemicalsSpecialty', :dest => 'Chemicals')
  XigniteIndustryMapping.create(:source => 'AdvertisingOrMarketingServices', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'CommercialPrintingOrForms', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'MiscellaneousCommercialServices', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'OfficeEquipmentOrSupplies', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'PersonnelServices', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'Homebuilding', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'BuildingProducts', :dest => 'Construction Materials')
  XigniteIndustryMapping.create(:source => 'ConstructionMaterials', :dest => 'Construction Materials')  
  XigniteIndustryMapping.create(:source => 'BeveragesAlcoholic', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'BeveragesNonAlcoholic', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'ConsumerSundries', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'ElectronicsOrAppliances', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'HomeFurnishings', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'HouseholdOrPersonalCare', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'OtherConsumerSpecialties', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'RecreationalProducts', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'Textiles', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'Tobacco', :dest => 'Consumer Products')
  XigniteIndustryMapping.create(:source => 'MedicalOrNursingServices', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'MedicalSpecialties', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'OtherConsumerServices', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'PublishingBooksOrMagazines', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'PublishingNewspapers', :dest => 'Consumer Discretionary Srvcs')
  XigniteIndustryMapping.create(:source => 'ContainersOrPackaging', :dest => 'Containers & Packaging')
  XigniteIndustryMapping.create(:source => 'FoodDistributors', :dest => 'Distributors')
  XigniteIndustryMapping.create(:source => 'MedicalDistributors', :dest => 'Distributors')
  XigniteIndustryMapping.create(:source => 'WholesaleDistributors', :dest => 'Distributors')
  XigniteIndustryMapping.create(:source => 'CatalogOrSpecialtyDistribution', :dest => 'Distributors')
  XigniteIndustryMapping.create(:source => 'ElectronicsDistributors', :dest => 'Distributors')
  XigniteIndustryMapping.create(:source => 'ElectricalProducts', :dest => 'Electrical Equipment')
  XigniteIndustryMapping.create(:source => 'ElectronicComponents', :dest => 'Electrical Equipment')
  XigniteIndustryMapping.create(:source => 'ElectronicEquipmentOrInstruments', :dest => 'Electrical Equipment')
  XigniteIndustryMapping.create(:source => 'ElectronicProductionEquipment', :dest => 'Electrical Equipment')
  XigniteIndustryMapping.create(:source => 'EngineeringAndConstruction', :dest => 'Engineering & Construction Svcs')
  XigniteIndustryMapping.create(:source => 'EnvironmentalServices', :dest => 'Engineering & Construction Svcs')
  XigniteIndustryMapping.create(:source => 'MoviesOrEntertainment', :dest => 'Recreation Facilities & Svcs')
  XigniteIndustryMapping.create(:source => 'FoodMajorDiversified', :dest => 'Travel Lodging & Dining')
  XigniteIndustryMapping.create(:source => 'FoodMeatOrFishOrDairy', :dest => 'Travel Lodging & Dining')
  XigniteIndustryMapping.create(:source => 'FoodRetail', :dest => 'Travel Lodging & Dining')
  XigniteIndustryMapping.create(:source => 'FoodSpecialtyOrCandy', :dest => 'Travel Lodging & Dining')
  XigniteIndustryMapping.create(:source => 'ForestProducts', :dest => 'Forest & Paper Products')
  XigniteIndustryMapping.create(:source => 'PulpAndPaper', :dest => 'Forest & Paper Products')
  XigniteIndustryMapping.create(:source => 'CasinosOrGaming', :dest => 'Travel Lodging & Dining')
  XigniteIndustryMapping.create(:source => 'HotelsOrResortsOrCruiselines', :dest => 'Travel Lodging & Dining')
  XigniteIndustryMapping.create(:source => 'Restaurants', :dest => 'Travel Lodging & Dining')
  XigniteIndustryMapping.create(:source => 'ManagedHealthCare', :dest => 'Health Care Facilities & Svcs')
  XigniteIndustryMapping.create(:source => 'HospitalOrNursingManagement', :dest => 'Health Care Facilities & Svcs')
  XigniteIndustryMapping.create(:source => 'ServicestotheHealthIndustry', :dest => 'Health Care Facilities & Svcs')
  XigniteIndustryMapping.create(:source => 'MiscellaneousManufacturing', :dest => 'ndustrial Services')
  XigniteIndustryMapping.create(:source => 'InsuranceBrokersOrServices', :dest => 'Insurance')
  XigniteIndustryMapping.create(:source => 'LifeOrHealthInsurance', :dest => 'Insurance')
  XigniteIndustryMapping.create(:source => 'MultiLineInsurance', :dest => 'Insurance')
  XigniteIndustryMapping.create(:source => 'PropertyOrCasualtyInsurance', :dest => 'Insurance')
  XigniteIndustryMapping.create(:source => 'SpecialtyInsurance', :dest => 'Insurance')
  XigniteIndustryMapping.create(:source => 'Steel', :dest => 'Iron & Steel')
  XigniteIndustryMapping.create(:source => 'MetalFabrication', :dest => 'Machinery')
  XigniteIndustryMapping.create(:source => 'IndustrialConglomerates', :dest => 'Manufactured Goods')
  XigniteIndustryMapping.create(:source => 'IndustrialMachinery', :dest => 'Manufactured Goods')
  XigniteIndustryMapping.create(:source => 'IndustrialSpecialties', :dest => 'Manufactured Goods')
  XigniteIndustryMapping.create(:source => 'ToolsAndHardware', :dest => 'Manufactured Goods')
  XigniteIndustryMapping.create(:source => 'Broadcasting', :dest => 'Media')
  XigniteIndustryMapping.create(:source => 'MediaConglomerates', :dest => 'Media')
  XigniteIndustryMapping.create(:source => 'CableOrSatelliteTV', :dest => 'Media')
  XigniteIndustryMapping.create(:source => 'Aluminum', :dest => 'Metals & Mining')
  XigniteIndustryMapping.create(:source => 'ContractDrilling', :dest => 'Metals & Mining')
  XigniteIndustryMapping.create(:source => 'OtherMetalsOrMinerals', :dest => 'Metals & Mining')
  XigniteIndustryMapping.create(:source => 'PreciousMetals', :dest => 'Metals & Mining')
  XigniteIndustryMapping.create(:source => 'Coal', :dest => 'Oil Gas & Coal')
  XigniteIndustryMapping.create(:source => 'GasDistributors', :dest => 'Oil Gas & Coal')
  XigniteIndustryMapping.create(:source => 'IntegratedOil', :dest => 'Oil Gas & Coal')
  XigniteIndustryMapping.create(:source => 'OilAndGasPipelines', :dest => 'Oil Gas & Coal')
  XigniteIndustryMapping.create(:source => 'OilAndGasProduction', :dest => 'Oil Gas & Coal')
  XigniteIndustryMapping.create(:source => 'OilfieldServicesOrEquipment', :dest => 'Oil Gas & Coal')
  XigniteIndustryMapping.create(:source => 'OilRefiningOrMarketing', :dest => 'Oil Gas & Coal')
  XigniteIndustryMapping.create(:source => 'RealEstateDevelopment', :dest => 'REIT')
  XigniteIndustryMapping.create(:source => 'RealEstateInvestmentTrusts', :dest => 'REIT')
  XigniteIndustryMapping.create(:source => 'InternetRetail', :dest => 'Retail')
  XigniteIndustryMapping.create(:source => 'SpecialtyStores', :dest => 'Retail')
  XigniteIndustryMapping.create(:source => 'DepartmentStores', :dest => 'Retail')
  XigniteIndustryMapping.create(:source => 'DiscountStores', :dest => 'Retail')
  XigniteIndustryMapping.create(:source => 'DrugstoreChains', :dest => 'Retail')
  XigniteIndustryMapping.create(:source => 'ElectronicsOrApplianceStores', :dest => 'Retail')
  XigniteIndustryMapping.create(:source => 'HomeImprovementChains', :dest => 'Retail')
  XigniteIndustryMapping.create(:source => 'Semiconductors', :dest => 'Semiconductors')
  XigniteIndustryMapping.create(:source => 'InternetSoftwareOrServices', :dest => 'Software')
  XigniteIndustryMapping.create(:source => 'PackagedSoftware', :dest => 'Software')
  XigniteIndustryMapping.create(:source => 'FinanceOrRentalOrLeasing', :dest => 'Specialty Finance')
  XigniteIndustryMapping.create(:source => 'FinancialConglomerates', :dest => 'Specialty Finance')
  XigniteIndustryMapping.create(:source => 'FinancialPublishingOrServices', :dest => 'Specialty Finance')
  XigniteIndustryMapping.create(:source => 'InvestmentBanksOrBrokers', :dest => 'Specialty Finance')
  XigniteIndustryMapping.create(:source => 'ComputerCommunications', :dest => 'Technology Services')
  XigniteIndustryMapping.create(:source => 'ComputerPeripherals', :dest => 'Technology Services')
  XigniteIndustryMapping.create(:source => 'ComputerProcessingHardware', :dest => 'Technology Services')
  XigniteIndustryMapping.create(:source => 'DataProcessingServices', :dest => 'Technology Services')
  XigniteIndustryMapping.create(:source => 'InformationTechnologyServices', :dest => 'Technology Services')
  XigniteIndustryMapping.create(:source => 'MajorTelecommunications', :dest => 'Telecom')
  XigniteIndustryMapping.create(:source => 'SpecialtyTelecommunications', :dest => 'Telecom')
  XigniteIndustryMapping.create(:source => 'TelecommunicationsEquipment', :dest => 'Telecom')
  XigniteIndustryMapping.create(:source => 'WirelessTelecommunications', :dest => 'Telecom')
  XigniteIndustryMapping.create(:source => 'AirFreightOrCouriers', :dest => 'Transportation & Logistics')
  XigniteIndustryMapping.create(:source => 'MarineShipping', :dest => 'Transportation & Logistics')
  XigniteIndustryMapping.create(:source => 'OtherTransportation', :dest => 'Transportation & Logistics')
  XigniteIndustryMapping.create(:source => 'Railroads', :dest => 'Transportation & Logistics')
  XigniteIndustryMapping.create(:source => 'Trucking', :dest => 'Transportation & Logistics')
  XigniteIndustryMapping.create(:source => 'TrucksOrConstructionOrFarmMachinery', :dest => 'Transportation & Logistics')
  XigniteIndustryMapping.create(:source => 'AlternativePowerGeneration', :dest => 'Utilities')
  XigniteIndustryMapping.create(:source => 'ElectricUtilities', :dest => 'Utilities')
  XigniteIndustryMapping.create(:source => 'WaterUtilities', :dest => 'Utilities')
end
